import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layouts/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative max-w-[1480px] mx-auto `}
      >
        <Header />
        <main className=" h-screen  pt-28 pb-14 flex w-full   ">

          {/* left  */}
          <div className=" w-[2%] flex flex-col h-full justify-center items-center gap-3 " >
            <div>FB</div>
            <div>IG</div>
            <div>X</div>
            <div>LN</div>
          </div>

          <div className=" flex justify-center w-[96%]  ">
            {children}
          </div>

          {/* right  */}
          <div className=" w-[2%] flex flex-col h-full justify-center items-center " >
            <p className=" text-gray-500 rotate-90 uppercase whitespace-nowrap ">Creative Developer</p>
          </div>
        </main>
        <footer className=" fixed bottom-0 left-0 right-0 h-10 bg-black "  >llllll</footer>
      </body>
    </html>
  );
}
